# Generated by Django 6.0.2 on 2026-02-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_noticia_destaque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='URL do Instagram')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='URL do YouTube')),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
